---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
I ask you riddles, tell you tales,  
But all our conversation fails.  
You never answer me again--  
I fear you're dumb, Matilda Jane!  
Matilda darling, when I call,  



## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
If I should die, think only this of me:  
   That there’s some corner of a foreign field  
That is for ever England.  There shall be  
   In that rich earth a richer dust concealed;  
A dust whom England bore, shaped, made aware,  
   Gave, once, her flowers to love, her ways to roam,  
A body of England’s, breathing English air,  
   Washed by the rivers, blest by suns of home.  
And think, this heart, all evil shed away,  
   A pulse in the eternal mind, no less  
     Gives somewhere back the thoughts by England given;  
Her sights and sounds; dreams happy as her day;  
   And laughter, learnt of friends; and gentleness,  
     In hearts at peace, under an English heaven.  
